---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - namespace.yml
  - keycloak-operator.yml
  - ingress.yml
  - secrets.yml
  - keycloak-db.yml
  - keycloak.yml