---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- path: host_alias.yml
  target:
    name: oauth2-proxy
- path: host_alias.yml
  target:
    name: regapp
- path: wait_for_kc.yml