---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nercra-kcdb-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/nercra-kcdb-pv
