---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nercra-kcdb-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: nercra-kcdb-pv
