---
apiVersion: v1
kind: ConfigMap
metadata:
  name: regapp-db-configmap
  labels:
    app.kubernetes.io/name: regapp-db-configmap
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
