---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: regapp-db
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: regapp
spec:
  lookupPolicy:
    local: true