---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: regapp
commonLabels:
  app.kubernetes.io/part-of: regapp
  
bases:
- ../../base

resources:
# - buildconfig.yml
- namespace.yml
- imagestream.yml
- pull_secret.yml
