---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- minikube_storageclass.yml
- ../../base

images:
  - name: image-registry.openshift-image-registry.svc:5000/regapp/regapp-db
    newName: mghpcc/regapp-db
  - name: image-registry.openshift-image-registry.svc:5000/regapp/regapp
    newName: mghpcc/regapp    

patches:
- path: replace_storageclass.json
  target:
    kind: StatefulSet   
# - path: add_hostaliases.yml
#   target:
#     kind: Deployment
- path: wait_for_kc.yml
- path: devel_switch.yml