---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets
resources:
  - ../../base
  - customkeys.yml
  # - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/controller.yaml
  - controller.yml