
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-configmap-kc
data:
  OAUTH2_PROXY_PROXY_PREFIX: /oauth2kc
  OAUTH2_PROXY_COOKIE_NAME: _oauth2_proxy_kc
  #OAUTH2_PROXY_COOKIE_DOMAIN: .mghpcc.org
  OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
  #OAUTH2_PROXY_PASS_WHITELIST_DOMAIN: "nerc.mghpcc.org"
  OAUTH2_PROXY_LOGIN_URL: https://keycloak.nerc.mghpcc.org/auth/realms/nerc/protocol/openid-connect/auth
  OAUTH2_PROXY_REDEEM_URL: https://keycloak.nerc.mghpcc.org/auth/realms/nerc/protocol/openid-connect/token
  OAUTH2_PROXY_PROFILE_URL: https://keycloak.nerc.mghpcc.org/auth/realms/nerc/protocol/openid-connect/userinfo
  OAUTH2_PROXY_VALIDATE_URL: https://keycloak.nerc.mghpcc.org/auth/realms/nerc/protocol/openid-connect/userinfo
  OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak.nerc.mghpcc.org/auth/realms/nerc
  OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
  OAUTH2_PROXY_UPSTREAMS: file:///dev/null
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_SCOPE: openid email profile
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-secret-kc
type: Opaque
data:
  #OAUTH2_PROXY_CLIENT_ID: regapp
  OAUTH2_PROXY_CLIENT_ID: cmVnYXBw
  #OAUTH2_PROXY_CLIENT_SECRET: dd7919cd-eb28-4795-81d0-8acbd38bf375
  OAUTH2_PROXY_CLIENT_SECRET: ZGQ3OTE5Y2QtZWIyOC00Nzk1LTgxZDAtOGFjYmQzOGJmMzc1
  #OAUTH2_PROXY_COOKIE_SECRET: dXc3ZHlZd0xsdnBrWkVVRVNLaW9BUT09
  OAUTH2_PROXY_COOKIE_SECRET: ZFhjM1pIbFpkMHhzZG5CcldrVlZSVk5MYVc5QlVUMDk=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-configmap-cilogon
data:
  OAUTH2_PROXY_PROXY_PREFIX: /oauth2cilogon
  OAUTH2_PROXY_COOKIE_NAME: _oauth2_proxy_cilogon
  #OAUTH2_PROXY_COOKIE_DOMAIN: .mghpcc.org
  OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
  OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
  OAUTH2_PROXY_PASS_WHITELIST_DOMAIN: "cilogon.org"
  OAUTH2_PROXY_LOGIN_URL: https://cilogon.org/authorize 
  OAUTH2_PROXY_REDEEM_URL: https://cilogon.org/oauth2/token
  OAUTH2_PROXY_PROFILE_URL: https://cilogon.org/oauth2/userinfo 
  OAUTH2_PROXY_VALIDATE_URL: https://cilogon.org/oauth2/userinfo 
  OAUTH2_PROXY_OIDC_ISSUER_URL: https://cilogon.org
  OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4188"
  OAUTH2_PROXY_UPSTREAMS: file:///dev/null
  OAUTH2_PROXY_PROVIDER: oidc
  OAUTH2_PROXY_SCOPE: openid email profile org.cilogon.userinfo
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-secret-cilogon
type: Opaque
data:
  # OAUTH2_PROXY_CLIENT_ID: cilogon:/client_id/ab05912d88d9f9cc5ea155accf420f3 
  OAUTH2_PROXY_CLIENT_ID: Y2lsb2dvbjovY2xpZW50X2lkL2FiMDU5MTJkODhkOWY5Y2M1ZWExNTVhY2NmNDIwZjM=
  # OAUTH2_PROXY_CLIENT_SECRET: C2z-thf2Ukj72dw65qXFP5yCeDZfQd4aWlYtK7nZXVTfyhZNprewJkwnE-_XmfZOgaPvAoTvZIkTk-6Zwar4Fg
  OAUTH2_PROXY_CLIENT_SECRET: QzJ6LXRoZjJVa2o3MmR3NjVxWEZQNXlDZURaZlFkNGFXbFl0SzduWlhWVGZ5aFpOcHJld0prd25FLV9YbWZaT2dhUHZBb1R2WklrVGstNlp3YXI0Rmc=
  # OAUTH2_PROXY_COOKIE_SECRET: dXc3ZHlZd0xsdnBrWkVVRVNLaW9BUT09
  OAUTH2_PROXY_COOKIE_SECRET: ZFhjM1pIbFpkMHhzZG5CcldrVlZSVk5MYVc5QlVUMDk=
