# skaffold.yaml
apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: nercra-skaffold
build:
  tagPolicy:
    sha256: {}
  local:
    push: true
  artifacts:
    # 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
    # - image: mghpcc/regapp-util
    - image: ghcr.io/culbert/regapp-util
      context: ../containers/regapp-util
    # - image: mghpcc/regapp-db
    - image: ghcr.io/culbert/regapp-db
      context: ../containers/regapp-db
    #- image: mghpcc/regapp
    - image: ghcr.io/culbert/regapp
      context: ..
      sync:
        infer:
          - "apps/**"
          - "config/**"
          - "jinja2/**"
          - "manage.py"
      docker:
        dockerfile: containers/regapp/Dockerfile
deploy:
  kustomize:
    paths: 
      - regapp/overlays/dev

  kubeContext: minikube
