---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nercra-radb-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/nercra-radb-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nercra-radb-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: nercra-radb-pv
