---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minikube_storageclass.yml
  - ../../base 

patches:
- path: replace_storageclass.json
  target:
    kind: StatefulSet   
